### ISSUE TITLE
تداخل متغیرهای CSS

### ISSUE THREAD

**Issue by fardm** [iSegaro/Translate-It#43]
سلام
وقت بخیر
یه مشکل هست. افزونه یه فایل CSS (theme.css) رو توی همه سایت‌ها لود می‌کنه و استایل اصلی سایت ها رو تغییر میده:
```css
body {
  background-color: var(--bg-color);
  color: var(--text-color);
}
```

https://github.com/user-attachments/assets/3159421c-5703-4b86-90b9-b9e469ba93c4

اگر ممکنه این محدود به صفحات خود افزونه باشه.
ممنون!
